# Generated by Django 5.2.9 on 2025-12-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='en', max_length=10, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50, verbose_name='Timezone'),
        ),
    ]
