# Generated by Django 5.2.9 on 2025-12-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_pre_notified',
            field=models.BooleanField(default=False, verbose_name='10-min Warning Sent'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='Deadline Missed Sent'),
        ),
    ]
